require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersController do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {name: "Foo Bar", fb_id: "12345", email: "test@example.com", number: "2223334444", college: "Pomona" }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "USER registration" do

    before do
      request.env["omniauth.auth"] = OmniAuth.config.mock_auth[:facebook]
      @hash = request.env["omniauth.auth"]
      @id = OmniAuth.config.mock_auth[:facebook][:uid]
    end

    it "should render new when a new user registers" do
      get :new
      assigns(:user).fb_id.should == @id
      response.should render_template('new')
    end

    it "should redirect_to :back when a old user returns" do
      @user = User.new_user_from_hash(@hash)
      @user.save
      request.env["HTTP_REFERER"] = '/requests/index'
      get :new
      assigns(:current_user).should == @user
      response.should redirect_to('/requests/index')
    end

  end

  describe "GET edit" do
    it "assigns the requested user as @user" do
      user = User.create! valid_attributes
      valid_session[:user_id] = user.id
      assigns(:user).should eq(user)
      get :edit, {:id => user.to_param}, valid_session
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new User" do
        expect {
          post :create, {:user => valid_attributes}, valid_session
        }.to change(User, :count).by(1)
      end

      it "assigns a newly created user as @user" do
        post :create, {:user => valid_attributes}, valid_session
        assigns(:user).should be_a(User)
        assigns(:user).should be_persisted
      end

      it "redirects to the created user" do
        post :create, {:user => valid_attributes}, valid_session
        response.should redirect_to(User.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user as @user" do
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        post :create, {:user => {}}, valid_session
        assigns(:user).should be_a_new(User)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        post :create, {:user => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user" do
        user = User.create! valid_attributes
        # Assuming there are no other users in the database, this
        # specifies that the User created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        valid_session[:user_id] = user.id
        User.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => user.to_param, :user => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested user as @user" do
        user = User.create! valid_attributes
        valid_session[:user_id] = user.id
        assigns(:user).should eq(user)
        put :update, {:id => user.to_param, :user => valid_attributes}, valid_session
      end

      it "redirects to the user" do
        user = User.create! valid_attributes
      valid_session[:user_id] = user.id
        response.should redirect_to(user)
        put :update, {:id => user.to_param, :user => valid_attributes}, valid_session
      end
    end

    describe "with invalid params" do
      it "assigns the user as @user" do
        user = User.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        assigns(:user).should eq(user)
        put :update, {:id => user.to_param, :user => {}}, valid_session
      end

      it "re-renders the 'edit' template" do
        user = User.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User.any_instance.stub(:save).and_return(false)
        response.should render_template("edit")
        put :update, {:id => user.to_param, :user => {}}, valid_session
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user" do
      user = User.create! valid_attributes
      valid_session[:user_id] = user.id
      expect {
        delete :destroy, {:id => user.to_param}, valid_session
      }.to change(User, :count).by(-1)
    end

    it "redirects to the users list" do
      user = User.create! valid_attributes
      valid_session[:user_id] = user.id
      response.should redirect_to(users_url)
      delete :destroy, {:id => user.to_param}, valid_session
    end
  end

end
